### PR TITLE
Trigger an error if a class declaration is missing in the configuration

### LINKED ISSUE #517: Doctrine Mapping seems to be broken
Related to  #385
### Environment
Symfony 4.2.4
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.45.2 = 3.45.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.15.0 = 3.15.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  = 2.0.1  Cache library
sonata-project/classification-bundle     3.8.0  = 3.8.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.16.1 = 3.16.1 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  = 2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5  = 1.1.5  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.3  = 3.8.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  = 2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.11.0 = 1.11.0 Lightweight Exporter library
sonata-project/formatter-bundle          3.5.0  ~ 4.1.2  Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.5.0  = 2.5.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.19.1 = 3.19.1 Symfony SonataMediaBundle
sonata-project/news-bundle               3.8.0  = 3.8.0  Symfony SonataNewsBundle
sonata-project/user-bundle               4.3.0  = 4.3.0  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/apache-pack          v1.0.1             = v1.0.1             A pack for Apache support in Symfony
symfony/asset                v4.2.4             = v4.2.4             Symfony Asset Component
symfony/browser-kit          v4.2.4             = v4.2.4             Symfony BrowserKit Component
symfony/cache                v4.2.4             = v4.2.4             Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               v4.2.4             = v4.2.4             Symfony Config Component
symfony/console              v4.2.4             = v4.2.4             Symfony Console Component
symfony/contracts            v1.0.2             = v1.0.2             A set of abstractions extracted out of the Symfony components
symfony/css-selector         v4.2.4             = v4.2.4             Symfony CssSelector Component
symfony/debug                v4.2.4             = v4.2.4             Symfony Debug Component
symfony/debug-bundle         v4.2.4             = v4.2.4             Symfony DebugBundle
symfony/debug-pack           v1.0.7             = v1.0.7             A debug pack for Symfony projects
symfony/dependency-injection v4.2.4             = v4.2.4             Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.2.4             = v4.2.4             Symfony Doctrine Bridge
symfony/dom-crawler          v4.2.4             = v4.2.4             Symfony DomCrawler Component
symfony/dotenv               v4.2.4             = v4.2.4             Registers environment variables from a .env file
symfony/event-dispatcher     v4.2.4             = v4.2.4             Symfony EventDispatcher Component
symfony/expression-language  v4.2.4             = v4.2.4             Symfony ExpressionLanguage Component
symfony/filesystem           v4.2.4             = v4.2.4             Symfony Filesystem Component
symfony/finder               v4.2.4             = v4.2.4             Symfony Finder Component
symfony/flex                 v1.2.0             = v1.2.0             Composer plugin for Symfony
symfony/form                 v4.2.4             = v4.2.4             Symfony Form Component
symfony/framework-bundle     v4.2.4             = v4.2.4             Symfony FrameworkBundle
symfony/http-foundation      v4.2.4             = v4.2.4             Symfony HttpFoundation Component
symfony/http-kernel          v4.2.4             = v4.2.4             Symfony HttpKernel Component
symfony/inflector            v4.2.4             = v4.2.4             Symfony Inflector Component
symfony/intl                 v4.2.4             = v4.2.4             A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lts                  dev-master c1affae = dev-master c1affae Enforces Long Term Supported versions of Symfony components
Package symfony/lts is abandoned, you should avoid using it. Use symfony/flex instead.
symfony/maker-bundle         v1.11.4            = v1.11.4            Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about...
symfony/monolog-bridge       v4.2.4             = v4.2.4             Symfony Monolog Bridge
symfony/monolog-bundle       v3.3.1             = v3.3.1             Symfony MonologBundle
symfony/options-resolver     v4.2.4             = v4.2.4             Symfony OptionsResolver Component
symfony/orm-pack             v1.0.6             = v1.0.6             A pack for the Doctrine ORM
symfony/panther              v0.3.0             = v0.3.0             A browser testing and web scraping library for PHP and Symfony.
symfony/phpunit-bridge       v4.2.4             = v4.2.4             Symfony PHPUnit Bridge
symfony/polyfill-ctype       v1.10.0            = v1.10.0            Symfony polyfill for ctype functions
symfony/polyfill-intl-icu    v1.10.0            = v1.10.0            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0            = v1.10.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.10.0            = v1.10.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process              v4.2.4             = v4.2.4             Symfony Process Component
symfony/profiler-pack        v1.0.4             = v1.0.4             A pack for the Symfony web profiler
symfony/property-access      v4.2.4             = v4.2.4             Symfony PropertyAccess Component
symfony/property-info        v4.2.4             = v4.2.4             Symfony Property Info Component
symfony/routing              v4.2.4             = v4.2.4             Symfony Routing Component
symfony/security-acl         v3.0.1             = v3.0.1             Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.2.4             = v4.2.4             Symfony SecurityBundle
symfony/security-core        v4.2.4             = v4.2.4             Symfony Security Component - Core Library
symfony/security-csrf        v4.2.4             = v4.2.4             Symfony Security Component - CSRF Library
symfony/security-guard       v4.2.4             = v4.2.4             Symfony Security Component - Guard
symfony/security-http        v4.2.4             = v4.2.4             Symfony Security Component - HTTP Integration
symfony/serializer           v4.2.4             = v4.2.4             Symfony Serializer Component
symfony/serializer-pack      v1.0.2             = v1.0.2             A pack for the Symfony serializer
symfony/stopwatch            v4.2.4             = v4.2.4             Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.5             = v3.2.5             Symfony SwiftmailerBundle
symfony/templating           v4.2.4             = v4.2.4             Symfony Templating Component
symfony/test-pack            v1.0.5             = v1.0.5             A pack for functional and end-to-end testing within a Symfony app
symfony/translation          v4.2.4             = v4.2.4             Symfony Translation Component
symfony/twig-bridge          v4.2.4             = v4.2.4             Symfony Twig Bridge
symfony/twig-bundle          v4.2.4             = v4.2.4             Symfony TwigBundle
symfony/validator            v4.2.4             = v4.2.4             Symfony Validator Component
symfony/var-dumper           v4.2.4             = v4.2.4             Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         v4.2.4             = v4.2.4             A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link             v4.2.4             = v4.2.4             Symfony WebLink Component
symfony/web-profiler-bundle  v4.2.4             = v4.2.4             Symfony WebProfilerBundle
symfony/web-server-bundle    v4.2.4             = v4.2.4             Symfony WebServerBundle
symfony/webpack-encore-pack  v1.0.3             = v1.0.3             A pack for Symfony Encore
symfony/yaml                 v4.2.4             = v4.2.4             Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.1.14
```

## Subject

The doctrine Mapping seems to be broken.
That's why the link with tags from Sonata Classification doesn't work and you get 

> No metadata found for property `Applcation\Sonata\NewsBundle\Entity\Post::$tags`. Please make sure your Doctrine mapping is properly configured

## Steps to reproduce

    clone my repo: https://github.com/FlorianKromer/SonataNewsBundle-issue
    composer install
    bin/console doctrine:schema:update -f 
    create a user: php bin/console fos:user:create testuser test@example.com p@ssword --super-admin
    login on the website
    go the news post list or try to create a new one

## Expected results
access to the post list / create post
## Actual results

this error: No metadata found for property App\Application\Sonata\NewsBundle\Entity\Post::$tags. Please make sure your Doctrine mapping is properly configured.

## Idea

The problem come from these lines:
https://github.com/sonata-project/SonataNewsBundle/blob/a9f7a7c41e4327ce2687606ddf1f596c0f64341d/src/DependencyInjection/SonataNewsExtension.php#L142-L146

Maybe it's not compatible with Flex ?
The problem is resolved if you delete them. (Btw you have to run again  schema:update) 

**edit**: In fact if  `    Sonata\NewsBundle\SonataNewsBundle::class => ['all' => true],` is called after : ApplicationSonataUserBundle,ApplicationSonataClassificationBundle in bundles.php it works ... but I still find the code above dangerous cause it fails silently

### PR DESCRIPTION
**Pull request by FlorianKromer**
## Subject

According the issue #517 we have to add more controls in order to prevent people to forget the tag and the collection class declarations.
That's why I add some information in the documentation and I add a trigger_error message.
Moreover I created a new test class : SonataNewsExtensionTest to test this PR.

I am targeting this branch, because this pull request is backwards comptatible.

Closes #517 , #385 

## Changelog

```markdown
### Added
- Added a new test class SonataNewsExtensionTest. Inspired by the SonataMediaExtensionTest, I extended AbstractExtensionTestCase to test if the association with media, user, tag, collection have been created according to a configuration
- A dependency to [matthiasnoback/symfony-dependency-injection-test
](https://packagist.org/packages/matthiasnoback/symfony-dependency-injection-test) 

### Changed
- src/DependencyInjection/SonataNewsExtension.php registerDoctrineMapping to add a trigger_error message
```

_this is my first PR, sorry if I forgot something_

### CODE REVIEW

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+                    'post' => Post::class,
+                    'comment' => Comment::class,
+                    'media' => Media::class,
+                    'user' => User::class,
+                ],
+            ];
+    }
+
+    /**
+     * {@inheritdoc}
```
Comment (core23) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]: Please remove this

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+        $tagAndCollectionDeclaration = [
+                'class' => [
+                        'collection' => \stdClass::class,
+                        'tag' => \stdClass::class,
+                ],
+            ];
+        $this->load(array_merge($minimalConfiguration, $tagAndCollectionDeclaration));
+        $collector = DoctrineCollector::getInstance();
+        //assert our model have associations
+        $this->assertCount(2, $collector->getAssociations());
```
Comment (core23) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]: Can you simplify this? This is not very readable

File: src/DependencyInjection/SonataNewsExtension.php [hunk 3]
```diff
@@ -141,6 +141,12 @@ public function registerDoctrineMapping(array $config)
 
         foreach ($config['class'] as $type => $class) {
             if (!class_exists($class)) {
+                /*
+                 * NEXT_MAJOR:
+                 * Throw an exception if the class is not defined
+                 */
+                @trigger_error('The class '.$class.' is not defined or doesn\'t exist. This is tolerated now but will be forbidden in 4.0', E_USER_DEPRECATED);
```
Comment (greg0ire) [inline src/DependencyInjection/SonataNewsExtension.php]:
```suggestion
                @trigger_error(sprintf(
                    'The "%s" class is not defined or does not exist. This is tolerated now but will be forbidden in 4.0',
                    $class
                ), E_USER_DEPRECATED);
```

Comment (greg0ire) [inline src/DependencyInjection/SonataNewsExtension.php]: What is the difference between not being defined and not existing?

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+     * {@inheritdoc}
+     */
+    protected function setUp(): void
+    {
+        parent::setUp();
+        $this->container->setParameter('kernel.bundles', []);
+    }
+
+    /**
+     * Test if the deprecation notice is trigger when the tag (or collection) class declaration is missing.
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]:
```suggestion
     * Test if the deprecation notice is triggered when the tag (or collection) class declaration is missing.
```

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+    public function testLoadWithoutTagWithoutCollection(): void
+    {
+        $this->load($this->getMinimalConfiguration());
+        $collector = DoctrineCollector::getInstance();
+
+        $this->assertEmpty($collector->getAssociations());
+    }
+
+    /**
+     * Test if the deprecation notice is trigger when the tag (or collection) class declaration is present.
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]:
```suggestion
     * Test if the deprecation notice is triggered when the tag (or collection) class declaration is present.
```

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 6]
```diff
@@ -0,0 +1,113 @@
...
+     * It shouldn't trigger a deprecation notice but doesn't break anything
+     * You should have 2 associations (Post, Comment).
+     * The Post model should have an associations with (Media, User, Collection, Tag).
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]:
```suggestion
     * The Post model should have an association with (Media, User, Collection, Tag).
```

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 7]
```diff
@@ -0,0 +1,113 @@
...
+        $minimalConfiguration = $this->getMinimalConfiguration();
+        $tagAndCollectionDeclaration = [
+                'class' => [
+                        'collection' => \stdClass::class,
+                        'tag' => \stdClass::class,
+                ],
+            ];
+        $this->load(array_merge($minimalConfiguration, $tagAndCollectionDeclaration));
+        $collector = DoctrineCollector::getInstance();
+        //assert our model have associations
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]:
```suggestion
        // assert our model has associations
```

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 8]
```diff
@@ -0,0 +1,113 @@
...
+        $this->assertCount(2, $collector->getAssociations());
+        $postManyToOneAssociation = $collector->getAssociations()[Post::class]['mapManyToOne'];
+        //assert the post model has  3 many to one associations (user,media,collection)
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]:
```suggestion
        // assert the post model has 3 many to one associations (user, media, collection)
```

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 9]
```diff
@@ -0,0 +1,113 @@
...
+        $this->assertCount(3, $postManyToOneAssociation);
+        $postManyToManyAssociation = $collector->getAssociations()[Post::class]['mapManyToMany'];
+        //assert the post model has  1 many to many associations (tag)
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]:
```suggestion
        // assert the post model has 1 many to many association (tag)
```

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 10]
```diff
@@ -0,0 +1,113 @@
...
+        $this->assertCount(1, $postManyToManyAssociation);
+        $postOneToManyAssociation = $collector->getAssociations()[Post::class]['mapOneToMany'];
+        //assert the post model has  1 one to many associations (comment)
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]:
```suggestion
        // assert the post model has 1 one to many associations (comment)
```

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 11]
```diff
@@ -0,0 +1,113 @@
...
+        $this->assertCount(1, $postOneToManyAssociation);
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]: What do you think about transforming comments into $message arguments?
```suggestion
        $this->assertCount(
            1,
            $postOneToManyAssociation,
            'The post model should have 1 one to many association (comment)'
        );
```

File: src/DependencyInjection/SonataNewsExtension.php (hunk 3 above)
Comment (FlorianKromer) [reply src/DependencyInjection/SonataNewsExtension.php]: Forget to declare 
```            
class:
        tag:        App\Application\Sonata\ClassificationBundle\Entity\Tag
```
is not the same as declare a class with a typo in the namespace. 
Maybe it will be easier for the developer to understand his/her mistake if we write these 2 possibilities.

File: tests/DependencyInjection/SonataNewsExtensionTest.php (hunk 1 above)
Comment (FlorianKromer) [reply tests/DependencyInjection/SonataNewsExtensionTest.php]: I did it like in SonataMedia
https://github.com/sonata-project/SonataMediaBundle/blob/a190425f516d613d3ff136f0dd15b04feb322f3f/tests/DependencyInjection/SonataMediaExtensionTest.php#L282-L303

As I use this configuration twice, I wanted to be DRY. Why this is not a good idea?

File: tests/DependencyInjection/SonataNewsExtensionTest.php (hunk 2 above)
Comment (FlorianKromer) [reply tests/DependencyInjection/SonataNewsExtensionTest.php]: I added getConfigurationWithTagWithCollection() which do the merge

File: tests/DependencyInjection/SonataNewsExtensionTest.php (hunk 11 above)
Comment (FlorianKromer) [reply tests/DependencyInjection/SonataNewsExtensionTest.php]: you are right, done !

File: src/DependencyInjection/SonataNewsExtension.php (hunk 3 above)
Comment (greg0ire) [reply src/DependencyInjection/SonataNewsExtension.php]: You mean writing the name of a class in the file, but forget to create the file with the class in it? Isn't that a bit unlikely?

File: tests/DependencyInjection/SonataNewsExtensionTest.php (hunk 1 above)
Comment (greg0ire) [reply tests/DependencyInjection/SonataNewsExtensionTest.php]: @core23 is not referring to the method, but to the phpdoc

File: tests/DependencyInjection/SonataNewsExtensionTest.php [hunk 12]
```diff
@@ -0,0 +1,112 @@
...
+use Sonata\EasyExtendsBundle\Mapper\DoctrineCollector;
+use Sonata\MediaBundle\Model\Media;
+use Sonata\NewsBundle\DependencyInjection\SonataNewsExtension;
+use Sonata\NewsBundle\Model\Comment;
+use Sonata\NewsBundle\Model\Post;
+use Sonata\UserBundle\Model\User;
+
+class SonataNewsExtensionTest extends AbstractExtensionTestCase
+{
+
```
Comment (greg0ire) [inline tests/DependencyInjection/SonataNewsExtensionTest.php]: Let's remove this line and let the build pass again
```suggestion
```

File: src/DependencyInjection/SonataNewsExtension.php (hunk 3 above)
Comment (FlorianKromer) [reply src/DependencyInjection/SonataNewsExtension.php]: For example : If you copy / paste the advanced configuration, but you don't run sonata extends on classification bundle. You 'll have:
```
class:
        tag:        Application\Sonata\ClassificationBundle\Entity\Tag
```
->  the tag class will be 'defined', but it doesn't really exist.

Comment (greg0ire) [reply src/DependencyInjection/SonataNewsExtension.php]: Oh oh that's a bit more likely indeed 👍
